// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVzypZBCFeVOEGnM0lkr16zI48CVM-Svc',
    appId: '1:578999573932:web:2c9cf53d034136eb486e09',
    messagingSenderId: '578999573932',
    projectId: 'staynear-7a71b',
    authDomain: 'staynear-7a71b.firebaseapp.com',
    storageBucket: 'staynear-7a71b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVtWLbAc-hu873pbf9vtDCcEhOARvxT-o',
    appId: '1:578999573932:android:411b8560a551ce4c486e09',
    messagingSenderId: '578999573932',
    projectId: 'staynear-7a71b',
    storageBucket: 'staynear-7a71b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkuzbLAThcNO1SRp1b_uClgMj65sRaEy4',
    appId: '1:578999573932:ios:ffd023304fa10dde486e09',
    messagingSenderId: '578999573932',
    projectId: 'staynear-7a71b',
    storageBucket: 'staynear-7a71b.firebasestorage.app',
    iosBundleId: 'com.example.staynear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkuzbLAThcNO1SRp1b_uClgMj65sRaEy4',
    appId: '1:578999573932:ios:ffd023304fa10dde486e09',
    messagingSenderId: '578999573932',
    projectId: 'staynear-7a71b',
    storageBucket: 'staynear-7a71b.firebasestorage.app',
    iosBundleId: 'com.example.staynear',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVzypZBCFeVOEGnM0lkr16zI48CVM-Svc',
    appId: '1:578999573932:web:884c0269ba956f91486e09',
    messagingSenderId: '578999573932',
    projectId: 'staynear-7a71b',
    authDomain: 'staynear-7a71b.firebaseapp.com',
    storageBucket: 'staynear-7a71b.firebasestorage.app',
  );
}
